### ISSUE TITLE
support new governance contract

### ISSUE THREAD

**Issue by yuan-finance** [yuan-finance/yuan-frontend#1]
由于YIP003 已经生效，所以前端需要将旧的governance合约地址: `0x712350ba552b4c84a602c7e635813da63ef5ba82` 替换了为新的governance合约地址: `0x6D5556b3CbD13375FAa08831588005900A966c60`,
新governance合约起始查询区块为11365200，此外为显示之前的proposal，仍需要查询旧的governance合约，所以现有的代码无需更改，但是需要复制一份，查询新的governance合约，具体修改位置为: src/yam-sdk/utils/index.js(line320): getProposals()

**Comment by ttthzy** [comment]
governance新合约地址要写入哪个配置文件吗？

**Comment by yuan-finance** [comment]
well done.
